// Regression test for a Biome `noUselessEscapeInRegex` autofix defect: an
// earlier pass silently rewrote the source line
// `query.toLowerCase().split(/\s+/)` to `.split(/s+/)` in the browser-side
// multi-field search (interactive-renderer.ts's `performAdvancedSearch`,
// embedded via generateInteractiveRendererJS()'s outer template literal),
// with zero test coverage catching it (the client-side code has no
// unit-test seam of its own — it only exists as a string generated by this
// class). The same defect class previously hit `\d`/other escaped
// character classes and was fixed once already (main's 3b3f6e64).
//
// Caveat verified while writing this test: `\s` has no special meaning
// inside a PLAIN template literal (` `` `, not a raw/String.raw literal),
// so the JS engine drops the backslash at parse time regardless of what
// the source says — `` `split(/\s+/)` `` and `` `split(/s+/)` `` evaluate
// to the IDENTICAL runtime string `"split(/s+/)"` inside a plain template
// literal. This means the source-text form checked below is the only
// place this defect is observable; it also means the browser-side search
// feature was ALREADY producing the collapsed `/s+/` pattern in `main`
// before this PR touched anything, and remains so — a pre-existing defect
// out of this PR's scope to fix (fixing it requires `\\s+`, a source
// change beyond "restore parity with main", and is left to whoever owns
// interactive-renderer.ts's client bundle next).
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

const SOURCE_PATH = join(dirname(fileURLToPath(import.meta.url)), 'interactive-renderer.ts');

describe('InteractiveTypedMindRenderer — multi-field search tokenization', () => {
  it('the performAdvancedSearch source line spells the whitespace-splitting regex with its backslash intact', () => {
    const source = readFileSync(SOURCE_PATH, 'utf8');

    // The correct source spelling must be present verbatim.
    assert.ok(
      source.includes('query.toLowerCase().split(/\\s+/);'),
      'expected performAdvancedSearch to spell split(/\\s+/) in source — an autofix pass previously dropped this backslash',
    );

    // The escape-dropped defect form must never appear in source, even
    // though (per the caveat above) it and the correct form currently
    // produce the same runtime string once embedded in the outer template
    // literal — the source spelling is what a future fix to the template-
    // literal escaping bug will depend on being correct.
    assert.ok(
      !source.includes('query.toLowerCase().split(/s+/);'),
      'performAdvancedSearch regressed to the escape-dropped split(/s+/) source form',
    );
  });

  it('the whitespace-splitting regex tokenizes multi-word search queries by whitespace, not by the letter "s"', () => {
    // Mirrors performAdvancedSearch's `query.toLowerCase().split(/\s+/)`
    // exactly — exercised directly (not through the browser bundle) so the
    // regex's actual behavior is pinned, not just its source spelling.
    const tokenize = (query: string): string[] => query.toLowerCase().split(/\s+/);

    assert.deepEqual(tokenize('user profile service'), ['user', 'profile', 'service']);
    assert.deepEqual(tokenize('  leading   and trailing  '), ['', 'leading', 'and', 'trailing', '']);
    assert.deepEqual(tokenize('single'), ['single']);

    // The defect regex (`/s+/`, missing the backslash) would instead split
    // on literal runs of "s" — e.g. "user service" contains no run of two-
    // or-more "s" characters, so it would NOT split at all under the
    // defect pattern. Assert the correct regex actually splits here.
    const words = tokenize('user service');
    assert.equal(words.length, 2, 'expected the query to split into 2 words on whitespace');
  });
});
