packages:
  - lib/*

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - keytar

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - arm64
    - x64
