name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/typed-mind-static-website/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build typed-mind parser
        working-directory: ./lib/typed-mind
        run: pnpm run build
        
      - name: Build typed-mind CLI
        working-directory: ./lib/typed-mind-cli
        run: pnpm run build
        
      - name: Build static website
        working-directory: ./lib/typed-mind-static-website
        run: pnpm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./lib/typed-mind-static-website/dist
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4